version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:14.5
    environment:
      POSTGRES_USER: luiz
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: store
    command: [ "postgres", "-c", "wal_level=logical" ]
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - network

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:5.4.9-1-ubi8
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - network

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:5.4.9-1-ubi8
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - network

  schema-registry:
    container_name: schema-registry
    image: confluentinc/cp-schema-registry:5.4.9-1-ubi8
    ports: [ '8081:8081' ]
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
    depends_on:
      - zookeeper
    networks:
      - network

  kafka-connect:
    container_name: kafka-connect
    image: confluentinc/cp-kafka-connect:5.4.9-1-ubi8
    ports: [ '8083:8083' ]
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka:9092
      CONNECT_GROUP_ID: kafka-connect
      CONNECT_REST_ADVERTISED_HOST_NAME: kafka-connect
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_CONFIG_STORAGE_TOPIC: connect-config-storage
      CONNECT_OFFSET_STORAGE_TOPIC: connect-offset-storage
      CONNECT_STATUS_STORAGE_TOPIC: connect-status-storage
      CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
    command:
      - bash
      - -c
      - confluent-hub install --no-prompt debezium/debezium-connector-postgresql:1.9.3 && /etc/confluent/docker/run
    depends_on:
      - kafka
    networks:
      - network

  control-center:
    container_name: control-center
    image: confluentinc/cp-enterprise-control-center:5.4.9-1-ubi8
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_CONNECT_CLUSTER: http://kafka-connect:8083
      CONTROL_CENTER_BOOTSTRAP_SERVERS: kafka:9092
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_CONNECT_HEALTHCHECK_ENDPOINT: '/connectors'
      CONTROL_CENTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      PORT: 9021
    depends_on:
      - kafka
      - kafka-connect
    networks:
      - network

volumes:
  postgres:


networks:
  network:
    name: network
